default_language_version:
  python: python3.10

ci:
  autofix_prs: false

repos:
  # Poetry
  - repo: https://github.com/python-poetry/poetry
    rev: 1.6.0
    hooks:
      - id: poetry-check
      - id: poetry-lock
        args: [--no-update]

  # Misc hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      ## Automatically fix issues
      - id: fix-byte-order-marker
      - id: trailing-whitespace
        stages: [commit]
        args: [ --markdown-linebreak-ext=md ]
        files: "\\.(py|txt|yaml|json|md|toml|lock|cfg|html|sh|js|yml)$"
      - id: mixed-line-ending
        files: "\\.(py|txt|yaml|json|md|toml|lock|cfg|html|sh|js|yml)$"
        args:
        - --fix=crlf
      - id: end-of-file-fixer

      ## Check for issues
      - id: check-merge-conflict
      - id: no-commit-to-branch
        stages: [commit]
        args: ['--pattern', '^(?!((fix|feat|refactor|docs)(\/\d+\-)[\w-]+)$).*']
      - id: check-yaml
        args: [--unsafe]

  # Dockerfile Linter
  - repo: https://github.com/AleksaC/hadolint-py
    rev: v2.12.0.3
    hooks:
      - id: hadolint
        args: [--ignore, DL3008]

  # CircleCI
  - repo: https://github.com/zahorniak/pre-commit-circleci.git
    rev: v0.6
    hooks:
    - id: circleci_validate
