version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:current
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS

    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Login to Docker Hub
          command: echo "$DOCKER_PASS" | docker login -u $DOCKER_USER --password-stdin
      - run:
          name: Build container
          command: docker build -t ldssa/academy-base:3.10 .
      - run:
          name: Verify build completed
          command: docker run ldssa/academy-base:3.10 /bin/bash -c "echo BUILDS OK"
      - run:
          name: Check that scipy links to OpenBLAS
          command: docker run ldssa/academy-base:3.10 python -c "from scipy.linalg import _fblas"
      - run:
          name: Check that numpy imports from bash shell
          command: docker run -t ldssa/academy-base:3.10 /bin/bash -c "python -c 'import numpy'"
      - run:
          name: Verify that numpy does not link to MKL
          command: docker run ldssa/academy-base:3.10 python -c "from numpy.distutils import system_info; assert system_info.get_info('mkl') == {}"
      - run:
          name: Run numpy unit tests
          command: docker run ldssa/academy-base:3.10 /bin/bash -c 'pip install pytest hypothesis; python -c "import numpy; numpy.test()"'
      - run:
          name: Push container to Docker Hub
          command:  docker push ldssa/academy-base:3.10
