version: 2
jobs:
  build:
#    docker:
#      - image: debian:stretch
    machine: true

    steps:

      - checkout

      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS

      - run: docker build -t ldssa/conda-base:latest .

      - run: docker push ldssa/conda-base:latest
