version: 2
jobs:
  build:
#    docker:
#      - image: debian:stretch
    machine: true

    steps:

      - checkout

      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS

      # build the conda version
#       - run: docker build -t ldssa/conda-base:latest .
#       - run: docker push ldssa/conda-base:latest

      # build the pip version
      - run: docker build -t ldssa/pip-base:latest ./Dockerfile-pip
      - run: docker push ldssa/pip-base:latest
